// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrmZAKFGEsCt_DXxDdinGefIyaC2elRoY',
    appId: '1:671835911052:web:5ca4e382ab79949f6ddca9',
    messagingSenderId: '671835911052',
    projectId: 'lanchonet-fc5a4',
    authDomain: 'lanchonet-fc5a4.firebaseapp.com',
    storageBucket: 'lanchonet-fc5a4.appspot.com',
    measurementId: 'G-Z05W8922ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ag_JyBsnHWbbY_Mcn1ErTd081cd2GLQ',
    appId: '1:671835911052:android:141bc6d41dbbd50d6ddca9',
    messagingSenderId: '671835911052',
    projectId: 'lanchonet-fc5a4',
    storageBucket: 'lanchonet-fc5a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvlzxQmXPNJfXv1nGtilRynvgxNxYLLc',
    appId: '1:671835911052:ios:1b1b23a479a82e1a6ddca9',
    messagingSenderId: '671835911052',
    projectId: 'lanchonet-fc5a4',
    storageBucket: 'lanchonet-fc5a4.appspot.com',
    iosClientId: '671835911052-p31egvinh47gmleuk6ldflj27uf9feds.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanchonet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvlzxQmXPNJfXv1nGtilRynvgxNxYLLc',
    appId: '1:671835911052:ios:1b1b23a479a82e1a6ddca9',
    messagingSenderId: '671835911052',
    projectId: 'lanchonet-fc5a4',
    storageBucket: 'lanchonet-fc5a4.appspot.com',
    iosClientId: '671835911052-p31egvinh47gmleuk6ldflj27uf9feds.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanchonet',
  );
}
